-- DBSTAPP.CASHACCOUNTY definition

-- Drop table

-- DROP TABLE DBSTAPP.CASHACCOUNTY;

CREATE TABLE DBSTAPP.CASHACCOUNTY (
	OWNER CHAR(32) NOT NULL,
	BALANCE DECIMAL(9,2),
	CURRENCYC CHAR(8),
	CONSTRAINT CASHACCOUNTY_PK PRIMARY KEY (OWNER)
);
CREATE UNIQUE INDEX ICASHACCOUNTY ON DBSTAPP.CASHACCOUNTY (OWNER);