-- DBSTAPP.FRANKFURT1 definition

-- Drop table

-- DROP TABLE DBSTAPP.FRANKFURT1;

CREATE TABLE DBSTAPP.FRANKFURT1 (
	CURRNKEY CHAR(5) NOT NULL,
	CURRNBASE CHAR(5),
	AMOUNT DECIMAL(9,2),
	RATES DECIMAL(10,2),
	LOADDT DATE NOT NULL,
	CONSTRAINT FRANKFURT1_PK PRIMARY KEY (CURRNKEY)
);
CREATE UNIQUE INDEX IFRANKFURT1 ON DBSTAPP.FRANKFURT1 (CURRNKEY);