-- STOCKTRD.PORTFOLIO definition

-- Drop table

-- DROP TABLE STOCKTRD.PORTFOLIO;

CREATE TABLE STOCKTRD.PORTFOLIO (
	OWNER VARCHAR(32) NOT NULL,
	TOTAL DOUBLE,
	ACCOUNTID VARCHAR(64),
	CONSTRAINT PORTFOLIO_PK PRIMARY KEY (OWNER)
);
CREATE UNIQUE INDEX PORTFOLIO_INDX1 ON STOCKTRD.PORTFOLIO (OWNER);
CREATE UNIQUE INDEX "PORTFOLI_#_7TU" 